steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '--build-arg'
      - 'VITE_API_URL=https://krashimitra-backend-694455455896.asia-south1.run.app'
      - '-t'
      - 'asia-south1-docker.pkg.dev/krashimitra-ai-2026/krashimitra/krashimitra-frontend'
      - '.'

images:
  - 'asia-south1-docker.pkg.dev/krashimitra-ai-2026/krashimitra/krashimitra-frontend'